/** Route paths are declared once so links, redirects and the sidebar never drift apart. */
export const ROUTES = {
  login: '/login',
  registerStore: '/register-store',
  registerStoreStatus: (id: string) => `/register-store/${id}`,
  onboarding: '/onboarding',
  onboardingComplete: '/onboarding/complete',
  personalDashboard: '/personal/dashboard',
  /** Calendar / daily plan hub (Growth Phase 3+). */
  personalPlan: '/personal/plan',
  /** Productivity hub: learning, habits, focus, social (Growth). */
  personalGrowth: '/personal/growth',
  personalGrowthTodos: '/personal/growth/todos',
  personalGrowthFocus: '/personal/growth/focus',
  personalGrowthHabits: '/personal/growth/habits',
  personalGrowthLearning: '/personal/growth/learning',
  personalGrowthLevel: '/personal/growth/level',
  personalGrowthAchievements: '/personal/growth/achievements',
  personalGrowthFriends: '/personal/growth/friends',
  personalGrowthChallenges: '/personal/growth/challenges',
  personalGrowthSocial: '/personal/growth/social',
  personalGrowthNotifications: '/personal/growth/notifications',
  personalGrowthReviews: '/personal/growth/reviews',
  /** Finance hub — wallets, history, budgets, saving goals, analytics. */
  personalFinance: '/personal/finance',
  /** Profile / account settings (replaces primary “Sozlamalar” tab). */
  personalProfile: '/personal/profile',
  /** @deprecated Prefer personalProfile — kept for deep links / redirects. */
  personalSettings: '/personal/settings',
  personalHistory: '/personal/history',
  personalBilling: '/personal/billing',
  personalReferral: '/personal/referral',
  personalAccounts: '/personal/accounts',
  personalIncome: '/personal/income',
  personalExpenses: '/personal/expenses',
  personalCategories: '/personal/categories',
  personalBudgets: '/personal/budgets',
  personalGoals: '/personal/goals',
  personalAnalytics: '/personal/analytics',
  personalRecurring: '/personal/recurring',
  personalDebts: '/personal/debts',
  personalNotifications: '/personal/notifications',
  platformPersonal: '/platform/personal',
  platformAccounts: '/platform/accounts',
  platformAccountsPersonal: '/platform/accounts/personal',
  platformAccountsBusiness: '/platform/accounts/business',
  platformAccountDetail: (id: string) => `/platform/accounts/w/${id}`,
  platformSubscriptions: '/platform/subscriptions',
  platformFinance: '/platform/finance',
  platformFinanceIncome: '/platform/finance/income',
  platformReferral: '/platform/referral',
  platformReferralUsers: '/platform/referral/users',
  platformReferralWithdrawals: '/platform/referral/withdrawals',
  platformReferralSettings: '/platform/referral/settings',
  platformOnboarding: '/platform/onboarding',
  platformOnboardingQuestions: '/platform/onboarding/questions',
  platformOnboardingAnswers: '/platform/onboarding/answers',
  platformOnboardingNeeds: '/platform/onboarding/needs',
  platformOnboardingSolutions: '/platform/onboarding/solutions',
  platformStoreRequests: '/platform/stores/requests',
  platformStoreRequestDetail: (id: string) => `/platform/stores/requests/${id}`,
  platformShops: '/platform/shops',
  platformShopsActive: '/platform/shops/active',
  platformShopsPendingPayment: '/platform/shops/pending-payment',
  platformShopsBlocked: '/platform/shops/blocked',
  platformShopDetail: (id: string) => `/platform/shops/${id}`,
  platformSubscriptionRequests: '/platform/subscription-requests',
  platformPayments: '/platform/payments',
  platformPaymentsPending: '/platform/payments/pending',
  platformPaymentsOverdue: '/platform/payments/overdue',
  platformPlans: '/platform/plans',
  platformExpenses: '/platform/expenses',
  platformPnl: '/platform/pnl',
  platformAnalytics: '/platform/analytics',
  platformAnalyticsStores: '/platform/analytics/stores',
  platformAnalyticsRevenue: '/platform/analytics/revenue',
  platformAnalyticsExpenses: '/platform/analytics/expenses',
  platformAnalyticsProfit: '/platform/analytics/profit',
  platformSettings: '/platform/settings',
  platformAccountDeletions: '/platform/account-deletions',
  billing: '/billing',
  storeReferral: '/referral',
  /** Compatibility aliases requested as /admin/... — same pages as /platform/... */
  adminStores: '/admin/stores',
  adminStoreDetail: (id: string) => `/admin/stores/${id}`,
  adminSubscriptionRequests: '/admin/subscription-requests',
  accessBlocked: '/access-blocked',
  dashboard: '/dashboard',
  sales: '/sales',
  saleNew: '/sales/new',
  saleDetail: (id: string) => `/sales/${id}`,
  saleEdit: (id: string) => `/sales/${id}/edit`,
  /** Assembly task inbox for workers with ASSEMBLER responsibility. */
  assemblyTasks: '/assembly-tasks',
  /** Delivery (shopir) operational inbox. */
  delivery: '/delivery',
  /** Sales where the signed-in worker is the seller. */
  mySales: '/my-sales',
  /** Signed-in seller commission report. */
  myReports: '/my-reports',
  /** Signed-in worker profile + activity summary. */
  profile: '/profile',
  /** Signed-in worker read-only financial ledger. */
  profileFinances: '/profile/finances',
  products: '/products',
  productDetail: (id: string) => `/products/${id}`,
  inventory: '/inventory',
  purchases: '/purchases',
  purchaseNew: '/purchases/new',
  purchaseDetail: (id: string) => `/purchases/${id}`,
  suppliers: '/suppliers',
  supplierDetail: (id: string) => `/suppliers/${id}`,
  customers: '/customers',
  customerDetail: (id: string) => `/customers/${id}`,
  expenses: '/expenses',
  workers: '/workers',
  workerNew: '/workers/new',
  workerDetail: (id: string) => `/workers/${id}`,
  workerEdit: (id: string) => `/workers/${id}/edit`,
  /** Admin-only worker financial ledger. */
  workerFinances: (id: string) => `/workers/${id}/finances`,
  /** Admin-only P&L vs ledger fee reconciliation. */
  workersReconciliation: '/workers/reconciliation',
  /** Admin-only worker compensation rules (configuration, not ledger). */
  workerCompensation: (id: string) => `/workers/${id}/compensation`,
  /** Admin-only read-only compensation preview (no finance side effects). */
  workerCompensationPreview: (id: string) => `/workers/${id}/compensation/preview`,
  masters: '/masters',
  masterDetail: (id: string) => `/masters/${id}`,
  debts: '/debts',
  reports: '/reports',
  /** Admin-only store audit trail. */
  audit: '/audit',
  settings: '/settings',
  /** Admin-only backup export / restore screen. */
  settingsBackup: '/settings/backup',
  /** Unlisted foundation diagnostics screen; reachable by URL, not from the sidebar. */
  systemCheck: '/system',
} as const;
