/** Route paths are declared once so links, redirects and the sidebar never drift apart. */
export const ROUTES = {
  login: '/login',
  registerStore: '/register-store',
  registerStoreStatus: (id: string) => `/register-store/${id}`,
  platformStoreRequests: '/platform/stores/requests',
  platformStoreRequestDetail: (id: string) => `/platform/stores/requests/${id}`,
  platformShops: '/platform/shops',
  platformShopsActive: '/platform/shops/active',
  platformShopsPendingPayment: '/platform/shops/pending-payment',
  platformShopsBlocked: '/platform/shops/blocked',
  platformShopDetail: (id: string) => `/platform/shops/${id}`,
  platformPayments: '/platform/payments',
  platformPaymentsPending: '/platform/payments/pending',
  platformPaymentsOverdue: '/platform/payments/overdue',
  platformPlans: '/platform/plans',
  platformExpenses: '/platform/expenses',
  platformPnl: '/platform/pnl',
  platformAnalytics: '/platform/analytics',
  platformAnalyticsStores: '/platform/analytics/stores',
  platformAnalyticsRevenue: '/platform/analytics/revenue',
  platformAnalyticsExpenses: '/platform/analytics/expenses',
  platformAnalyticsProfit: '/platform/analytics/profit',
  platformSettings: '/platform/settings',
  billing: '/billing',
  accessBlocked: '/access-blocked',
  dashboard: '/dashboard',
  sales: '/sales',
  saleNew: '/sales/new',
  saleDetail: (id: string) => `/sales/${id}`,
  /** Assembly task inbox for workers with ASSEMBLER responsibility. */
  assemblyTasks: '/assembly-tasks',
  /** Sales where the signed-in worker is the seller. */
  mySales: '/my-sales',
  /** Signed-in worker profile + activity summary. */
  profile: '/profile',
  products: '/products',
  productDetail: (id: string) => `/products/${id}`,
  inventory: '/inventory',
  purchases: '/purchases',
  purchaseNew: '/purchases/new',
  purchaseDetail: (id: string) => `/purchases/${id}`,
  suppliers: '/suppliers',
  supplierDetail: (id: string) => `/suppliers/${id}`,
  customers: '/customers',
  customerDetail: (id: string) => `/customers/${id}`,
  expenses: '/expenses',
  workers: '/workers',
  workerNew: '/workers/new',
  workerDetail: (id: string) => `/workers/${id}`,
  workerEdit: (id: string) => `/workers/${id}/edit`,
  /** Admin-only worker financial ledger. */
  workerFinances: (id: string) => `/workers/${id}/finances`,
  /** Admin-only worker compensation rules (configuration, not ledger). */
  workerCompensation: (id: string) => `/workers/${id}/compensation`,
  /** Admin-only read-only compensation preview (no finance side effects). */
  workerCompensationPreview: (id: string) => `/workers/${id}/compensation/preview`,
  masters: '/masters',
  masterDetail: (id: string) => `/masters/${id}`,
  debts: '/debts',
  reports: '/reports',
  /** Admin-only store audit trail. */
  audit: '/audit',
  settings: '/settings',
  /** Admin-only backup export / restore screen. */
  settingsBackup: '/settings/backup',
  /** Unlisted foundation diagnostics screen; reachable by URL, not from the sidebar. */
  systemCheck: '/system',
} as const;
