import { Router } from 'express';

import { accountsRouter } from '../modules/accounts/accounts.routes.js';
import { onboardingRouter, platformOnboardingRouter } from '../modules/personal-finance/onboarding/onboarding.routes.js';
import { personalBillingRouter } from '../modules/personal-finance/billing/personal-billing.routes.js';
import { personalLedgerRouter } from '../modules/personal-finance/ledger/personal-ledger.routes.js';
import { personalPlanningRouter } from '../modules/personal-finance/planning/personal-planning.routes.js';
import { personalAnalyticsRouter } from '../modules/personal-finance/analytics/personal-analytics.routes.js';
import { personalDebtsRouter } from '../modules/personal-finance/debts/personal-debts.routes.js';
import { personalNotificationsRouter } from '../modules/personal-finance/notifications/personal-notifications.routes.js';
import { personalPlanRouter } from '../modules/personal-finance/plan/personal-plan.routes.js';
import { personalGrowthTodoRouter } from '../modules/personal-finance/growth/personal-growth-todo.routes.js';
import { personalGrowthFocusRouter } from '../modules/personal-finance/growth/personal-growth-focus.routes.js';
import { personalGrowthHabitsRouter } from '../modules/personal-finance/growth/personal-growth-habits.routes.js';
import { personalGrowthLearningRouter } from '../modules/personal-finance/growth/personal-growth-learning.routes.js';
import { personalGrowthXpRouter } from '../modules/personal-finance/growth/personal-growth-xp.routes.js';
import { personalGrowthAchievementsRouter } from '../modules/personal-finance/growth/personal-growth-achievements.routes.js';
import { personalGrowthFriendsRouter } from '../modules/personal-finance/growth/personal-growth-friends.routes.js';
import { personalGrowthChallengesRouter } from '../modules/personal-finance/growth/personal-growth-challenges.routes.js';
import { personalGrowthSocialRouter } from '../modules/personal-finance/growth/personal-growth-social.routes.js';
import { personalGrowthNotificationsRouter } from '../modules/personal-finance/growth/personal-growth-notifications.routes.js';
import { personalGrowthReviewsRouter } from '../modules/personal-finance/growth/personal-growth-reviews.routes.js';
import { personalGrowthPremiumRouter } from '../modules/personal-finance/growth/personal-growth-premium.routes.js';
import { personalRecurringRouter } from '../modules/personal-finance/recurring/personal-recurring.routes.js';
import { platformPersonalRouter } from '../modules/personal-finance/stats/personal-stats.routes.js';
import { platformAccountsRouter } from '../modules/platform-accounts/platform-accounts.routes.js';
import { platformReferralsRouter, referralsRouter } from '../modules/referrals/referrals.routes.js';
import { analyticsRouter } from './analytics.routes.js';
import { auditRouter } from './audit.routes.js';
import { authRouter } from './auth.routes.js';
import { backupsRouter } from './backups.routes.js';
import { dashboardRouter } from './dashboard.routes.js';
import { debtsRouter } from './debts.routes.js';
import { expenseCategoriesRouter, expensesRouter } from './expenses.routes.js';
import { customersRouter } from './customers.routes.js';
import { healthRouter } from './health.routes.js';
import { inventoryRouter } from './inventory.routes.js';
import { productCategoriesRouter, productsRouter } from './products.routes.js';
import { meRouter } from './me.routes.js';
import { platformBillingRouter, storeAccessRouter } from './platform-billing.routes.js';
import { storeBillingRouter } from './store-billing.routes.js';
import { platformShopsRouter } from './platform-shops.routes.js';
import { platformStoreRequestsRouter } from './platform-store-requests.routes.js';
import { purchasesRouter, suppliersRouter } from './purchasing.routes.js';
import { storeRequestsRouter } from './store-requests.routes.js';
import { reportsRouter } from './reports.routes.js';
import { settingsRouter } from './settings.routes.js';
import { assemblyTasksRouter, salesRouter } from './sales.routes.js';
import { workerFinancesRouter } from './worker-finances.routes.js';
import { workersRouter } from './workers.routes.js';

/**
 * Every route in the application mounts here under `/api`.
 * Feature routers are added as each phase lands.
 */
export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/accounts', accountsRouter);
apiRouter.use('/onboarding', onboardingRouter);
apiRouter.use('/personal', personalBillingRouter);
apiRouter.use('/personal', personalLedgerRouter);
apiRouter.use('/personal', personalPlanningRouter);
apiRouter.use('/personal', personalAnalyticsRouter);
apiRouter.use('/personal', personalRecurringRouter);
apiRouter.use('/personal', personalDebtsRouter);
apiRouter.use('/personal', personalNotificationsRouter);
apiRouter.use('/personal', personalPlanRouter);
apiRouter.use('/personal', personalGrowthTodoRouter);
apiRouter.use('/personal', personalGrowthFocusRouter);
apiRouter.use('/personal', personalGrowthHabitsRouter);
apiRouter.use('/personal', personalGrowthLearningRouter);
apiRouter.use('/personal', personalGrowthXpRouter);
apiRouter.use('/personal', personalGrowthAchievementsRouter);
apiRouter.use('/personal', personalGrowthFriendsRouter);
apiRouter.use('/personal', personalGrowthChallengesRouter);
apiRouter.use('/personal', personalGrowthSocialRouter);
apiRouter.use('/personal', personalGrowthNotificationsRouter);
apiRouter.use('/personal', personalGrowthReviewsRouter);
apiRouter.use('/personal', personalGrowthPremiumRouter);
apiRouter.use('/referrals', referralsRouter);
apiRouter.use('/platform/referrals', platformReferralsRouter);
apiRouter.use('/platform/personal', platformPersonalRouter);
apiRouter.use('/platform/accounts', platformAccountsRouter);
apiRouter.use('/platform/onboarding', platformOnboardingRouter);
apiRouter.use('/store-requests', storeRequestsRouter);
apiRouter.use('/platform/store-requests', platformStoreRequestsRouter);
apiRouter.use('/platform/shops', platformShopsRouter);
apiRouter.use('/platform', platformBillingRouter);
apiRouter.use('/store-access', storeAccessRouter);
apiRouter.use('/billing', storeBillingRouter);
apiRouter.use('/me', meRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/sales', salesRouter);
apiRouter.use('/assembly-tasks', assemblyTasksRouter);
apiRouter.use('/customers', customersRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/product-categories', productCategoriesRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/suppliers', suppliersRouter);
apiRouter.use('/purchases', purchasesRouter);
apiRouter.use('/debts', debtsRouter);
apiRouter.use('/workers', workersRouter);
apiRouter.use('/worker-finances', workerFinancesRouter);
apiRouter.use('/expenses', expensesRouter);
apiRouter.use('/expense-categories', expenseCategoriesRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/backups', backupsRouter);
apiRouter.use('/audit', auditRouter);
